import React from 'react';

const TermsAndPrivacy = () => {
    return (
        <div>
            <div className="container">
                <h1 className='text-center'>Privacy Policy</h1>

                <div className="row" style={{ textAlign: 'justify' }}>
                    <div className="col-12 col-md-6" >
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                    </div>
                    <div className="col">
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>

                    </div>
                </div>


                {/* // terms and condition  */}
                <h1 className='text-center'>Terms And Condition</h1>

                <div className="row" style={{textAlign:'justify'}}>
                    <div className="col-12 col-md-6" >
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                    </div>
                    <div className="col">
                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quod eveniet ab exercitationem veniam molestias quia dolores non laudantium est temporibus? Culpa maiores et cupiditate distinctio officiis incidunt nisi voluptate. Nulla nihil neque enim reprehenderit cum inventore quos numquam, libero magni dolores hic fugiat molestiae dolorum, laudantium aspernatur pariatur provident? Quae eum cum eveniet odio nihil dolores reprehenderit, quod dignissimos accusantium.</p>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo repellat, earum est illum voluptas dolore dolores eligendi nam tenetur corrupti in inventore numquam esse eos sunt beatae obcaecati tempore fuga repellendus blanditiis dolorem provident voluptatem repudiandae. Nobis voluptates enim voluptatem aliquid consectetur vero, itaque, eveniet quisquam quia accusantium a iusto, fugit hic. Natus officia animi eos, exercitationem dicta beatae nihil libero aut dolorum obcaecati deleniti consequuntur accusantium. Earum culpa sunt aliquid porro totam aperiam ex ullam minus. Sint voluptates quisquam fuga aliquid perspiciatis. Nihil quod porro, facilis ipsa minus officia magnam reiciendis in incidunt distinctio, obcaecati consequatur, maxime saepe fuga.</p>
                       
                    </div>
                </div>

            </div>
        </div>
    );
};

export default TermsAndPrivacy;